### ISSUE TITLE
Background won't load

### ISSUE THREAD

**Issue by YosoraLife** [Villhellm/lovelace-animated-background#10]
Hi, thank you for creating this plugin. It looks great, but i cant seem to get it to work. I get this error:

> Uncaught DOMException: Failed to execute 'insertAdjacentHTML' on 'Element': The element has no parent.

Can you tell me what I am doing wrong?

**Comment by Villhellm** [comment]
What browser are you using, what version of HA, and are you on the most recent release of the module?

**Comment by YosoraLife** [comment]
I juse vivaldi (chrome based) as browser and i run the newest version, HA 0.108.4 and I run the latest update from 2 hours ago

**Comment by YosoraLife** [comment]
oww wait, on chrome it runs fine and also on the phone so it seems to be a browser issue

**Comment by Villhellm** [comment]
Try updating Vivaldi to see if that fixes it. I just installed it to try and recreate the error, but it ran fine.

**Comment by YosoraLife** [comment]
Yep, that seemed to fixed the issue hahah, thanks man!

**Comment by Villhellm** [comment]
No problem 👍
