### ISSUE TITLE
Sun, snow, wind and........ rain?

### ISSUE THREAD

**Issue by mcinnes01** [Villhellm/lovelace-animated-background#2]
Hi

First of all, awesome project, really love the video backgrounds, especially with the sync to weather status. From the available weather statuses I imagine you live in a lovely place, maybe some tropical island or somewhere where its just nice all the time. And whilst I love the fact things default to some beautiful sunny background, give me solace from the torrential downpour, mostly like going on outside.... I wondered if you could help us less fortunate at least be reminded of the reality of what is going on outside. At the very least so I stop wearing shorts all the time.

Here in Manchester, UK the weather is fairly changeable, usually between "Rainy" and "Cloudy". It would also be interesting if there were perhaps fog, snow, windy, thunderstorms (I'm not entirely sure on all the naming in DarkSky).

As an aside, I notice that DarkSky reports "Clear Night" to which there are options, but I wondered if there is anything I can do to just deal with night perhaps relating to sun set rather than the weather status and be able to display some night videos?

Thanks again for the great project.

Andy

**Comment by Villhellm** [comment]
The included HTML files and states are just examples. They aren't meant to be the only option. You are free to modify/change/add more files to suit your particular needs.

You use an `input_text` entity that changes your background based on more than one entity. You would just need to make a few automations to update the input text when the relevant entities change state.

**Comment by Villhellm** [comment]
I'm going to close this since providing video files is out of scope for this project.

**Comment by SeLLeRoNe** [comment]
Just my 2 cents, keep in mind that any modification will be overwritten by HACS on each update, so maybe use a different folder for your customized versions ;)

**Comment by Villhellm** [comment]
Was that intended for me? I'm not sure what customized version you're talking about.

**Comment by SeLLeRoNe** [comment]
Nope, more for the author of the issue :)

If you customize the "html" files that loads the various mp4, you need to keep in mind that on each update HACS will overwrite those with the ones that comes from this GIT repo.

Sorry if I wasn't clear enough.

Andrea

**Comment by Villhellm** [comment]
Oh yes, good point. I try to emphasize that the files are just examples. If you make changes they should be moved to a different location. I'll make a differently worded note in the README.
