### ISSUE TITLE
Make Removing Existing Background a Configurable Option

### ISSUE THREAD

**Issue by flexage** [Villhellm/lovelace-animated-background#29]
Love your work on this.

I see you've done some good code around setting any existing css background to `transparent`.

My setup has a scenario where I'm using a background image, and a semi-transparent background colour on it, to give it a glassy/opaque look that matches my theme, and helps mute the background image so it doesn't interfere with the ui.

The CSS I'm using is essentially this one liner:
```
background: linear-gradient(#241b2fdd, #241b2fdd), center / cover no-repeat  url("/local/backgrounds/synthwave-2.jpg") fixed;
```

The effect can be seen in this screenshot:

<img width="1920" alt="Screenshot 2020-05-20 at 2 38 32 am" src="https://user-images.githubusercontent.com/1283019/82395400-63701e80-9a43-11ea-9464-2413efa348ca.png">

It would be great to be able to replicate this effect whilst using your video background plugin.

**Describe the solution you'd like**
It would be great if we could add a config setting, that allows us to disable setting the background to transparent (in the `removeDefaultBackground()` function.

I guess you would probably still default to removing any default background (as this is probably the most common expectation when using this), but having the ability to disable that would allow me to modify the CSS I used above, to something like the following, which only sets the partially transparent background, and not also the background image as before:
```
background: linear-gradient(#241b2fdd, #241b2fdd);
```

That way, I can still have the purple overlaying the video, as to dull it down on mute it's visiblility, and not interfere with the UI elements on top.

Thanks again for your great work.

**Comment by Villhellm** [comment]
Added in release v0.6.1

**Comment by flexage** [comment]
Top man, you have my sincere thanks!
