### ISSUE TITLE
Support for Casting

### ISSUE THREAD

**Issue by undulattice** [Villhellm/lovelace-animated-background#30]
Hey.

Got this up and running. Looks great. :-)
I was looking to get cast a Lovelace panel to my Chromecast when it's idle. The casting works, but there's no video in the background.
I'm using Nabu Casa for remote access, don't know if that's an issue with casting? Wouldn't think so though...

Any chance you could implement? 

Thanks

Ray

**Comment by Villhellm** [comment]
Sorry, I don't think this is possible. I think the rendering for cast is very stripped down for speed. Lots of stuff gets cut, including animated background, unfortunately.
