### ISSUE TITLE
Misleading console message when user is not included

### ISSUE THREAD

**Issue by markusressel** [Villhellm/lovelace-animated-background#31]
**Describe the bug**
When limiting the animated dashboard to a specific user (or a list), opening the Home Assistant GUI and the user is not in the list, the log just states:
```
No configuration found for this dashboard
```
which is quite misleading.
Turning on the debug mode I actually got this message:
```
Animated Background DEBUG: Current user: Markus Ressel is not included
```

**Your Animated Background configuration**

I used the default config, with a limit to a user that was is not present in my Home Assistant instance (typo).

**Version Numbers**

  - Home Assistant: 0.111.2
  - Animated Background:  v0.6.1

**Browser console log**
see above

**To Reproduce**
see above

**Expected behavior**
Print the "user" message instead of the "dashboard" one.

**Device (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version latest...

**Screenshots**
n/a

**Comment by Villhellm** [comment]
If an exclusion is found then no configuration is passed on to the rendering step, which is why the message says "no configuration found.". Debug mode exists to give you more detail on how the configuration is being handled and should be used when setting up a more advanced config.
