### ISSUE TITLE
per view condition - idea

### ISSUE THREAD

**Issue by C0NTi** [Villhellm/lovelace-animated-background#4]
First off I love this plugin makes my dashboard more striking.

I have no idea how possible this would be but do you think there could be scope for conditional backgrounds based on current view as well as an entity's state

I have a gaming, security, weather, light etc etc views and it would look awesome.

I could have a different dynamic background for each tab that shows a relevant background based on an appropriate entity state for that view

**Comment by Villhellm** [comment]
I like this idea! I will start working on it soon, but PRs are welcome if anyone wants to take the wheel on this one

**Comment by matt1t** [comment]
Just loaded this and getting animated-background.js:7:0 SyntaxError: expected expression, got '<

I would love to use this plugin.  I tried both the manual setup and the HACS, both give the same error

**Comment by Villhellm** [comment]
Latest update adds this option. Please feel free to help me test it and let me know if anything goes wrong
