### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by GregoryVandromme** [Villhellm/lovelace-animated-background#44]
**Describe the bug**
Hi, my backgrounds won't show on Home Assistant, I've tried everything I can think of to fix it (clearing my cache completely reinstalling home assistant and hacs etc. nothing gives.

**Your Animated Background configuration**

animated_background:
  default_url: 'https://cdn.flixel.com/flixel/ypy8bw9fgw1zv2b4htp2.hd.mp4'
  entity: weather.home
  state_url:
    sunny:
      - 'https://cdn.flixel.com/flixel/hlhff0h8md4ev0kju5be.hd.mp4'
      - 'https://cdn.flixel.com/flixel/zjqsoc6ecqhntpl5vacs.hd.mp4'
      - 'https://cdn.flixel.com/flixel/jvw1avupguhfbo11betq.hd.mp4'
      - 'https://cdn.flixel.com/flixel/8cmeusxf3pkanai43djs.hd.mp4'
      - 'https://cdn.flixel.com/flixel/guwb10mfddctfvwioaex.hd.mp4'
    partlycloudy:
      - 'https://cdn.flixel.com/flixel/13e0s6coh6ayapvdyqnv.hd.mp4'
      - 'https://cdn.flixel.com/flixel/aorl3skmssy7udwopk22.hd.mp4'
      - 'https://cdn.flixel.com/flixel/qed6wvf2igukiioykg3r.hd.mp4'
      - 'https://cdn.flixel.com/flixel/3rd72eezaj6d23ahlo7y.hd.mp4'
      - 'https://cdn.flixel.com/flixel/9m11gd43m6qn3y93ntzp.hd.mp4'
      - 'https://cdn.flixel.com/flixel/hrkw2m8eofib9sk7t1v2.hd.mp4'
    cloudy:
      - 'https://cdn.flixel.com/flixel/13e0s6coh6ayapvdyqnv.hd.mp4'
      - 'https://cdn.flixel.com/flixel/aorl3skmssy7udwopk22.hd.mp4'
      - 'https://cdn.flixel.com/flixel/qed6wvf2igukiioykg3r.hd.mp4'
      - 'https://cdn.flixel.com/flixel/3rd72eezaj6d23ahlo7y.hd.mp4'
      - 'https://cdn.flixel.com/flixel/9m11gd43m6qn3y93ntzp.hd.mp4'
      - 'https://cdn.flixel.com/flixel/hrkw2m8eofib9sk7t1v2.hd.mp4'
    mostlycloudy:
      - 'https://cdn.flixel.com/flixel/e95h5cqyvhnrk4ytqt4q.hd.mp4'
      - 'https://cdn.flixel.com/flixel/l2bjw34wnusyf5q2qq3p.hd.mp4'
      - 'https://cdn.flixel.com/flixel/rrgta099ulami3zb9fd2.hd.mp4'
    clear-night:
      - 'https://cdn.flixel.com/flixel/x9dr8caygivq5secll7i.hd.mp4'
      - 'https://cdn.flixel.com/flixel/v26zyfd6yf0r33s46vpe.hd.mp4'
      - 'https://cdn.flixel.com/flixel/ypy8bw9fgw1zv2b4htp2.hd.mp4'
      - 'https://cdn.flixel.com/flixel/rosz2gi676xhkiw1ut6i.hd.mp4'
    fog:
      - 'https://cdn.flixel.com/flixel/vwqzlk4turo2449be9uf.hd.mp4'
      - 'https://cdn.flixel.com/flixel/5363uhabodwwrzgnq6vx.hd.mp4'
    rainy: 'https://cdn.flixel.com/flixel/f0w23bd0enxur5ff0bxz.hd.mp4'
title: Home
views:
  - path: default_view
    cards:
      - type: media-control
        entity: media_player.kitchen_speaker
      - type: media-control
        entity: media_player.living_room
      - type: media-control
        entity: media_player.office_speaker
      - type: entities
        entities:
          - binary_sensor.rpi_power_status
          - binary_sensor.updater
        title: Binary Sensor
      - type: media-control
        entity: media_player.living_room_2
      - type: entities
        entities:
          - person.gregory
        title: Person
      - type: entities
        entities:
          - remote.living_room
        title: Remote
      - type: entities
        entities:
          - sensor.hp_photosmart_7520_series
          - sensor.hp_photosmart_7520_series_black_ink
          - sensor.hp_photosmart_7520_series_cyan_ink
          - sensor.hp_photosmart_7520_series_light_black_ink
          - sensor.hp_photosmart_7520_series_magenta_ink
          - sensor.hp_photosmart_7520_series_yellow_ink
          - sensor.hacs
        title: Sensor
      - type: entities
        entities:
          - sun.sun
        title: Sun
      - type: weather-forecast
        entity: weather.home
        show_forecast: true

**Version Numbers**
"Latest" is not a version number

  - Home Assistant: core-2021.3.4
  - Animated Background: v0.6.3

**Browser console log**
​ A preload for 'http://homeassistant.local:8123/frontend_latest/core.a16e4a28.js' is found, but is not used because the script type does not match.
(anonymous) @ default_view:1
​ A preload for 'http://homeassistant.local:8123/frontend_latest/app.52350e7c.js' is found, but is not used because the script type does not match.
(anonymous) @ default_view:1
:8123/hacsfiles/lovelace-animated-background/animated-background.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
chunk.7ade96a9da5d055f2747.js:575 Uncaught (in promise) http://homeassistant.local:8123/hacsfiles/lovelace-animated-background/animated-background.js
:8123/logbook:1 The resource http://homeassistant.local:8123/frontend_latest/app.52350e7c.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
:8123/logbook:1 The resource http://homeassistant.local:8123/frontend_latest/core.a16e4a28.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
​ [ttyd] websocket connection opened
​ [ttyd] WebGL renderer enabled
​ [object Object],[object Object],[object Object]
:8123/lovelace:1 Autofocus processing was blocked because a document already has a focused element.

**Device (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome Beta
 - Version 90.0.4430.51

**Comment by Shalobee** [comment]
looks like you are missing your user list:

```
animated_background:
  default_url: /local/backgrounds/ypy8bw9fgw1zv2b4htp2.hd.mp4
  included_users:
    - user1
    - user2
  entity: weather.home
```

if the user isn't listed as displayed name then it won't work. For example I have a user for my wall mounted tablet called wallpanel with a display name of Wall Panel and it will only show up if i put Wall Panel for the included_users:
