### ISSUE TITLE
expected expression, got '<'

### ISSUE THREAD

**Issue by matt1t** [Villhellm/lovelace-animated-background#5]
Just loaded this and getting animated-background.js:7:0 SyntaxError: expected expression, got '<

I would love to use this plugin. I tried both the manual setup and the HACS, both give the same error

**Comment by Villhellm** [comment]
What browser are you using and what does your configuration look like?

**Comment by matt1t** [comment]
Wow, didn't expect a response this fast thanks!
Firefox 73.0.1 (64-bit) most all javascript options are turned on looking at about:config
I've also tried in IE, Chrome and Edge, no luck

My lovelace config is such:
animated_background:
  default_url: >-
    /local/community/lovelace-animated-background/background-animations/sunny.html
  entity: weather.dark_sky
  included_users:
    - Home
    - Matt
  state_url:
    clear-night: >-
      /local/community/lovelace-animated-background/background-animations/night.html
    cloudy: >-
      /local/community/lovelace-animated-background/background-animations/cloudy.html
    fog: >-
      /local/community/lovelace-animated-background/background-animations/fog.html
    mostlycloudy: >-
      /local/community/lovelace-animated-background/background-animations/mostlycloudy.html
    partlycloudy: /community/lovelace-animated-background/background-animations/cloudy.html
    sunny: >-
      /local/community/lovelace-animated-background/background-animations/sunny.html
resources:
  - type: module
    url: /local/community/lovelace-animated-background/animated-background.js

I can pull the html files in a browser at those locations

I just caught another error on the javascript:
http://192.168.0.115:8123/local/community/lovelace-animated-background/animated-background.js:70:25 TypeError: hass.states[animatedConfig.entity] is undefined

**Comment by Villhellm** [comment]
I remember some people reporting that it doesn’t work with Firefox. The original error you had looked familiar.

If that is your config then you’re missing a lot of indentation. Spaces in yaml are key. Make sure to wrap any yaml in a code block so formatting isn’t lost. If you are using weather.dark_sky make sure you have the dark sky integration installed and that the weather.dark_sky entity shows up in your states entity list

**Comment by matt1t** [comment]
Thank again for the reply.  The copy and paste messed up the yaml formatting. Noted about Firefox.  I do have dark_sky, however they are listed as sensors I do not see one as weather.dark_sky.

That may be my issue.  I'll try and go find it.

**Comment by matt1t** [comment]
Ok, I had the sensor installed, I now have the weather.dark_sky working and showing up in my states entity list.  Looks like I'm missing somthing simple on this now:

http://192.168.0.115:8123/local/community/lovelace-animated-background/animated-background.js:70:25 TypeError: hass.states[animatedConfig.entity] is undefined

I've tried setting the state, but keep seeing this in the log

**Comment by matt1t** [comment]
Sigh, I got it.  The states did not match.  The state was partlycloudy, I changed it to mostlycloudy and it loaded.  Its working now.  Thanks for the replies, I appreciate it!

-Matt
