### ISSUE TITLE
Local stored animated backgrounds??

### ISSUE THREAD

**Issue by mwitlox** [Villhellm/lovelace-animated-background#52]
Hi! Is it possible to use a local stored background? Cannot find a way to do this :( Tried a few things but no luck. Maybe possible already? More a question how to do it the a new feature. Hope someone can help me out! Really like this animated backgrounds!

**Comment by mwitlox** [comment]
Nevermind! Found a solution. 

Put it in the www folder then use:
/local/backgrounds-animated/sunny/1234.hd.mp4

**Comment by djqpaz** [comment]
@mwitlox  thank you for finding this..... the key to this was changing the relative path from www/ to /local/ 
example if you copy the path you get this....  www/images/viewscapes/BlueSky.mp4 but the path needs to be listed as 

/local/images/viewscapes/BlueSky.mp4

thanks again!!!
